# Code Attribution Badges For LLMs

## Alpaca 7B

![Code Generated By Alpaca 7B](https://img.shields.io/badge/Code%20Generated%20By-Alpaca%207B-blue)

`![Code Generated By Alpaca 7B](https://img.shields.io/badge/Code%20Generated%20By-Alpaca%207B-blue)`

## Claude 3.5

![Code Generated By Claude 3.5](https://img.shields.io/badge/Code%20Generated%20By-Claude%203.5-blue)

`![Code Generated By Claude 3.5](https://img.shields.io/badge/Code%20Generated%20By-Claude%203.5-blue)`

## Command R

![Code Generated By Command R](https://img.shields.io/badge/Code%20Generated%20By-Command%20R-blue)

`![Code Generated By Command R](https://img.shields.io/badge/Code%20Generated%20By-Command%20R-blue)`

## DBRX

![Code Generated By DBRX](https://img.shields.io/badge/Code%20Generated%20By-DBRX-blue)

`![Code Generated By DBRX](https://img.shields.io/badge/Code%20Generated%20By-DBRX-blue)`

## Falcon 180B

![Code Generated By Falcon 180B](https://img.shields.io/badge/Code%20Generated%20By-Falcon%20180B-blue)

`![Code Generated By Falcon 180B](https://img.shields.io/badge/Code%20Generated%20By-Falcon%20180B-blue)`

## Gemma

![Code Generated By Gemma](https://img.shields.io/badge/Code%20Generated%20By-Gemma-blue)

`![Code Generated By Gemma](https://img.shields.io/badge/Code%20Generated%20By-Gemma-blue)`

## Gemini 1.5

![Code Generated By Gemini 1.5](https://img.shields.io/badge/Code%20Generated%20By-Gemini%201.5-ff69b4)

`![Code Generated By Gemini 1.5](https://img.shields.io/badge/Code%20Generated%20By-Gemini%201.5-ff69b4)`

## GPT-4o

![Code Generated By GPT-4o](https://img.shields.io/badge/Code%20Generated%20By-GPT-4o-blue)

`![Code Generated By GPT-4o](https://img.shields.io/badge/Code%20Generated%20By-GPT-4o-blue)`

## Grok-1

![Code Generated By Grok-1](https://img.shields.io/badge/Code%20Generated%20By-Grok--1-blue)

`![Code Generated By Grok-1](https://img.shields.io/badge/Code%20Generated%20By-Grok--1-blue)`

## Inflection-2.5

![Code Generated By Inflection-2.5](https://img.shields.io/badge/Code%20Generated%20By-Inflection-2.5-blue)

`![Code Generated By Inflection-2.5](https://img.shields.io/badge/Code%20Generated%20By-Inflection-2.5-blue)`

## Jamba

![Code Generated By Jamba](https://img.shields.io/badge/Code%20Generated%20By-Jamba-blue)

`![Code Generated By Jamba](https://img.shields.io/badge/Code%20Generated%20By-Jamba-blue)`

## Llama 3.1

![Code Generated By Llama 3.1](https://img.shields.io/badge/Code%20Generated%20By-Llama%203.1-blue)

`![Code Generated By Llama 3.1](https://img.shields.io/badge/Code%20Generated%20By-Llama%203.1-blue)`

## Mixtral 8x22B

![Code Generated By Mixtral 8x22B](https://img.shields.io/badge/Code%20Generated%20By-Mixtral%208x22B-blue)

`![Code Generated By Mixtral 8x22B](https://img.shields.io/badge/Code%20Generated%20By-Mixtral%208x22B-blue)`

## Mistral 7B

![Code Generated By Mistral 7B](https://img.shields.io/badge/Code%20Generated%20By-Mistral%207B-blue)

`![Code Generated By Mistral 7B](https://img.shields.io/badge/Code%20Generated%20By-Mistral%207B-blue)`

## Nemotron-4

![Code Generated By Nemotron-4](https://img.shields.io/badge/Code%20Generated%20By-Nemotron--4-blue)

`![Code Generated By Nemotron-4](https://img.shields.io/badge/Code%20Generated%20By-Nemotron--4-blue)`

## PaLM 2

![Code Generated By PaLM 2](https://img.shields.io/badge/Code%20Generated%20By-PaLM%202-blue)

`![Code Generated By PaLM 2](https://img.shields.io/badge/Code%20Generated%20By-PaLM%202-blue)`

## Phi-3

![Code Generated By Phi-3](https://img.shields.io/badge/Code%20Generated%20By-Phi-3-blue)

`![Code Generated By Phi-3](https://img.shields.io/badge/Code%20Generated%20By-Phi-3-blue)`

## Pythia

![Code Generated By Pythia](https://img.shields.io/badge/Code%20Generated%20By-Pythia-blue)

`![Code Generated By Pythia](https://img.shields.io/badge/Code%20Generated%20By-Pythia-blue)`

## Sora

![Code Generated By Sora](https://img.shields.io/badge/Code%20Generated%20By-Sora-ff69b4)

`![Code Generated By Sora](https://img.shields.io/badge/Code%20Generated%20By-Sora-ff69b4)`

## Stable LM 2

[![Stable LM 2 Badge](https://img.shields.io/badge/Stable-LM_2-brightgreen)](shields.io)
